[package]
name = "arcdps_bindings"
version = "0.1.7"
authors = ["Greaka <mrgreaka@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.4"

[dependencies.winapi]
version = "0.3"
features = ["std", "minwindef", "ntdef", "windef"]